services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rinha
    ports:
      - 5432:5432
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.7GB'

  cache:
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
    networks:
      - rinha

  api1:
    image: duck/rinha-backend:1.0.0-SNAPSHOT
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: rinha
      QUARKUS_DATASOURCE_PASSWORD: 123456
      QUARKUS_HTTP_PORT: 80
      CACHE_HOST: cache
    depends_on:
      - db
      - cache
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.9GB'

  api2:
    image: duck/rinha-backend:1.0.0-SNAPSHOT
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/rinha
      QUARKUS_DATASOURCE_USERNAME: rinha
      QUARKUS_DATASOURCE_PASSWORD: 123456
      QUARKUS_HTTP_PORT: 80
      CACHE_HOST: cache
    depends_on:
      - db
      - cache
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.9GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "api1"
      - "api2"
    ports:
      - "9999:9999"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

networks:
  rinha:
    driver: bridge